find un-managed mocks
sanposhiho/gomockhandler pull request #65
Opened 2021-09-18 17:20 UTC by riita10069

This PR ensures that the check command has a one-to-one correspondence between gomockhandler.json and the actual mock generated by gomock.
In other words, it finds zombie mocks. (A zombie mock is a mock generated by gomock but not managed by gomockhandler.)
And It can also find mocks which are managed by gomockhandler but not generated

2021-09-18 17:23 UTC, riita10069 commented
#61

2021-09-19 00:31 UTC, sanposhiho requested changes
Thanks for nice contribution! 

I left some comments. Please check when you are available 👍

2021-09-19 00:31 UTC, sanposhiho commented on internal/command/check.go
> +		fmt.Fprintf(os.Stderr, "There are un-managed mocks!!\nThe list of them: %v\n", zombieList)
nits

```suggestion
		fmt.Fprintf(os.Stderr, "[WARN] Some mocks are un-managed by gomockhandler: %v\n", zombieList)
```

2021-09-19 00:31 UTC, sanposhiho commented on internal/zombie/checker.go
> +		eg.Go(func() error {
We have to use `sem.Release(1)`after this line otherwise deadlock

```
defer sem.Release(1)
```

2021-09-19 00:31 UTC, sanposhiho commented on internal/zombie/checker.go
> +				key := lines[1][11:]
It is better to use the path of the mock file as a key. 
This is because we cannot get this key when mockgen change the format of mock file in the future. And we don't want to limit the versions of gomock that users can use.

2021-09-19 00:31 UTC, sanposhiho commented on internal/command/check.go
> +					fmt.Fprintf(os.Stderr, "[ERROR] mock is not up to date. destination: %s\n", key)
It is good idea, we can find configured but un-generated mock. 👍 

nits:

```suggestion
					fmt.Fprintf(os.Stderr, "[ERROR] mock has not been generated. destination: %s\n", key)
```

2021-09-19 00:31 UTC, sanposhiho commented on internal/command/check.go
> +					fmt.Fprintf(os.Stderr, "[ERROR] mock is not up to date. destination: %s\n", key)
nits:

```suggestion
					fmt.Fprintf(os.Stderr, "[ERROR] mock has not been generated. destination: %s\n", key)
```

2021-09-19 00:36 UTC, sanposhiho commented on internal/command/check.go
> +				if ok := zombieChecker.Search(key); !ok {
We have to do this check after this line: https://github.com/sanposhiho/gomockhandler/blob/master/internal/command/check.go#L71

This is because gomockhandler has the option `target_dir`.

2021-09-19 00:36 UTC, sanposhiho commented on internal/command/check.go
> +				if ok := zombieChecker.Search(key); !ok {
(same as https://github.com/sanposhiho/gomockhandler/pull/65/files#r711660619)

2021-09-19 00:58 UTC, sanposhiho commented
And you may already know about it, but we can check the behaviour of gomockhandler on /playground dir.

I wrote a contribution guide for that.
https://github.com/sanposhiho/gomockhandler/blob/master/CONTRIBUTING.md

2021-09-19 05:23 UTC, riita10069 commented on internal/zombie/checker.go
> +	ConcurrencyNum = 32
Don't you mean runtime.NumCPU?

2021-09-19 05:34 UTC, riita10069 commented on internal/zombie/checker.go
> +				key := lines[1][11:]
So does that mean we use destination as the Key of the Map?

2021-09-19 05:52 UTC, sanposhiho commented on internal/zombie/checker.go
> +				key := lines[1][11:]
> use destination as the Key of the Map?
Yes!

2021-09-19 05:56 UTC, sanposhiho commented on internal/zombie/checker.go
> +	ConcurrencyNum = 32
No

> execute user-level Go code simultaneously. There is no limit to the number of threads that can be blocked in system calls on behalf of Go code; those do not count against the GOMAXPROCS limit. This package's GOMAXPROCS function queries and changes the limit.
https://pkg.go.dev/runtime

And its default value is runtime.NumCPU :)

> It defaults to the value of runtime.NumCPU. 

https://pkg.go.dev/runtime#GOMAXPROCS


For example, upper limit of concurrency for `go test` command is `GOMAXPROCS`.
https://github.com/golang/go/blob/master/src/cmd/go/internal/test/test.go#L256

2021-09-19 06:06 UTC, riita10069 commented on internal/zombie/checker.go
> +	ConcurrencyNum = 32
I can't understand what the return value of runtime.GOMAXPROCS(0) means.
I think it is same value as runtime.NumCPU. Because that's the default.

2021-09-19 06:20 UTC, sanposhiho commented on internal/zombie/checker.go
> +	ConcurrencyNum = 32
GOMAXPROCS can be passed from environment variables and user can change it.

And, it means that
> The GOMAXPROCS variable limits the number of operating system threads that can execute user-level Go code simultaneously. There is no limit to the number of threads that can be blocked in system calls on behalf of Go code; those do not count against the GOMAXPROCS limit. This package's GOMAXPROCS function queries and changes the limit.
https://pkg.go.dev/runtime#hdr-Environment_Variables

2021-09-19 06:21 UTC, sanposhiho commented on internal/zombie/checker.go
> +	ConcurrencyNum = 32
runtime.GOMAXPROCS(0) returns the current GOMAXPROCS
> If n < 1, it does not change the current setting
https://pkg.go.dev/runtime#GOMAXPROCS

2021-09-22 11:58 UTC, riita10069 commented on internal/command/check.go
> +				if ok := zombieChecker.Search(key); !ok {
In Source Mode, it is returning immediately and will not move to #L71.

Why can't I use the current implementation?

2021-09-22 12:02 UTC, riita10069 commented on internal/command/check.go
> +				if ok := zombieChecker.Search(key); !ok {
I decided to give up on the parallelism for now.

2021-09-22 12:23 UTC, riita10069 commented
Verified that it works locally.
Should we implement automated tests?

2021-09-22 12:45 UTC, sanposhiho commented on internal/command/check.go
> +				if ok := zombieChecker.Search(key); !ok {
two reasons why I think it is better to move it to L84.

- we don't want to write the same logic two times. `zombieChecker.Search()` is needed for both sourcemode and reflectmode and it will be executed L84 even if we don't execute it here.
- we don't want to run `zombieChecker.Search()` if destination don't match with `target_dir`

Yes, as you said, we can find un-generated mocks here. But we can find it even if we move it to L84, and the time cost remains the same in both cases. 

Are there any other reasons you think it is better to execute `zombieChecker.Search()` here?

2021-09-22 12:46 UTC, sanposhiho reviewed
thanks for fixing some places

2021-09-22 12:46 UTC, sanposhiho commented on internal/command/check.go
> +				isFail = true
need `return nil` after this maybe?

2021-09-22 12:49 UTC, riita10069 commented on internal/command/check.go
> +				if ok := zombieChecker.Search(key); !ok {
Because in Source Mode if it returns at L61.., L84 is not executed.

2021-09-22 12:50 UTC, sanposhiho commented
> Should we implement automated tests?

Of course, if have tests, it is great. :)

But, I don't write any tests so far, because of feeling めんどくさい... 
So if you also feel that, I say nothing about test on this PR. And I will write tests someday....

2021-09-22 13:01 UTC, riita10069 commented
I empathize with you so much about めんどくさい lol.
Because A virtual file system may need to be implemented for e2e testing.
So I would like to think about e2e testing as the other PR.

2021-09-22 15:46 UTC, sanposhiho commented on internal/command/check.go
> +				if ok := zombieChecker.Search(key); !ok {
Aha, OK. Now I understood your thought. 
What you want to say is we should check un-generated mock before source checksum check, right? That's a fair point. 👍 

It is ok that sourceChecksum check is on here because it does only skip. But with the current code, we print an un-generated error for mocks on non-target dir. It's what we don't want to.

So let's move sourceChecksum check after L89 and do this check only when `m.Mode == model.SourceMode` so that we can delete L51-55.

2021-09-22 16:52 UTC, riita10069 commented on internal/command/check.go
> +				if ok := zombieChecker.Search(key); !ok {
OK, I'll do so

2021-09-23 03:06 UTC, sanposhiho commented on internal/zombie/checker.go
> +	hash map[string]bool
IMO we can use the more appropriate name on this `hash` field (because it doesn't have a hash.)

`isManagedMock` or `managedMockMap` is a more understandable name, maybe? 
(I don't have the best idea. If you can think of a better name, please use it :))

2021-09-24 05:11 UTC, riita10069 commented on internal/command/check.go
> +		fmt.Fprintf(os.Stderr, "failed to find mock list generated by gomock: %v\n", err)
IMO:
Exit(1) should not be executed by some goroutine.
Exit of the whole process should be limited to a specific line of the main function.
However, it is possible for any goroutine to write to StdOut, StdErr.
The reason is to make it easier to control the termination of any goroutine properly.

You don't think so?

2021-09-24 05:17 UTC, riita10069 commented on internal/command/check.go
> +		fmt.Fprintf(os.Stderr, "failed to find mock list generated by gomock: %v\n", err)
I noticed that the Check command uses log.Fatal for error handling, so it is better to follow it. so, I'll do so.

2021-09-25 06:17 UTC, sanposhiho commented on internal/command/check.go
> +		fmt.Fprintf(os.Stderr, "failed to find mock list generated by gomock: %v\n", err)
> I noticed that the Check command uses log.Fatal for error handling, so it is better to follow it. so, I'll do so.

---

(off topic, you don't need to reply to it)

> Exit(1) should not be executed by some goroutine.

This is definitely yes. In many case we should not call Exit() on goroutine.

> Exit of the whole process should be limited to a specific line of the main function.

(On huge programs, it is better to do so, but) This is partially No (in my knowledges. Plz correct me if I wrong or I miss something 🙏 )

Most of the reasons why we should not use Exit() is because defer funcs will not be executed when Exit(). 
In other words, we can use Exit() if we don't use defer funcs on the caller funcs.

2021-09-25 06:23 UTC, sanposhiho approved these changes
Looks good 👍 
Thanks for your big contribution!!

2021-09-25 06:39 UTC, sanposhiho commented
@riita10069 I changed the branch protection rule so that this PR can be merged. 
Please merge it If you can.

2021-09-25 06:52 UTC, riita10069 commented
Thanks for your review.
I don't have repository privileges, so I can't merge.
Only those with write access to this repository can merge pull requests.

2021-09-25 06:54 UTC, sanposhiho commented
> Only those with write access to this repository can merge pull requests.

Aha, Okay. (I forgot about an access right)
I'll merge it.

2021-09-25 06:54 UTC, merged